### ISSUE TITLE
Get user's feed

### ISSUE THREAD

**Issue by flybeach** [jlobos/instagram-web-api#10]
I can't fetch user's media feed by specifing user id (pk)?

**Comment by timolins** [comment]
Does `client.getUserByUsername()` work for you?

**Comment by flybeach** [comment]
of course, it will work. but your API doesn't support the way to get username by means like hopefully hashtag or something else.
so how can I get username to call getUserByUsername()?

**Comment by timolins** [comment]
Is there a reason why you only have access to the user id? I don't think an endpoint like this exists in their api.

I will close this issue for now – let me know if you find something which makes this possible!
