### ISSUE TITLE
Problem in login (UnhandledPromiseRejectionWarning: StatusCodeError: 400 - "Bad request")

### ISSUE THREAD

**Issue by mirlannur** [jlobos/instagram-web-api#118]
My code worked well, but, recently started throwing this exception in login: 
"UnhandledPromiseRejectionWarning: StatusCodeError: 400 - "Bad request" "
Have tryed #97 . Still not working

Any idea?

**Comment by welber91** [comment]
Same problem

**Comment by benkauffman** [comment]
it looks like instagram is encoding passwords before they are submitted to the login endpoint. my work around for the time being was to just login and grab the payload from the login request and update the library to match (make sure you URL decode first):
![instagram snippet](https://user-images.githubusercontent.com/16448205/82129336-aea1dd00-9776-11ea-8911-e812ea2e3c88.png)

**Comment by jdgabriel** [comment]
how to solve this problem using this lib?

**Comment by eoboite** [comment]
same issue

**Comment by welber91** [comment]
Thanks @benkauffman for the work around.

**Comment by anakis** [comment]
I notice that this **enc_password** are composed by `#PWD_INSTAGRAM_BROWSER:0:CURRENT_TIMESTAMP:YOUR_PLAIN_PASSWORD`. 

For now, I fork and publish a work around[publish a work around](https://www.npmjs.com/package/@anakis/instagram-web-api)

**Comment by revall** [comment]
> I notice that this **enc_password** are composed by `#PWD_INSTAGRAM_BROWSER:0:CURRENT_TIMESTAMP:YOUR_PLAIN_PASSWORD`.
> 
> For now, I fork and [publish a work around](https://www.npmjs.com/package/@anakis/instagram-web-api)

@anakis Good job, please make PR with your fix.

**Comment by vikasvmads** [comment]
getting the same problem.

Please help to solve it.

**Comment by anakis** [comment]
@vikasvmads Did you try the solution proposed above?

**Comment by vikasvmads** [comment]
The solution which  is given by @benkauffman?

**Comment by codexJoin** [comment]
Hello guys!, i solves this problem, and created an method to crypt password,
Just visit: https://github.com/codexJoin/InstagramCrypto

**Comment by vikasvmads** [comment]
I have done the same procedure but getting authenticated flag: false

Here is the screenshot

![Screenshot 2020-05-20 at 2 15 41 PM](https://user-images.githubusercontent.com/4836379/82425646-6cdda300-9aa4-11ea-934f-9bfc3270fb72.png)
![Screenshot 2020-05-20 at 2 15 50 PM](https://user-images.githubusercontent.com/4836379/82425662-749d4780-9aa4-11ea-8ef6-f9a1e6dfd38f.png)

**Comment by vikasvmads** [comment]
Working now Thanks

**Comment by benkauffman** [comment]
Dude. Your username and password are literally in plain text in that screenshot.

Ben Kauffman - Principal
360.909.0203 . KrashidBuilt
https://krashidbuilt.com

**Comment by iampratap** [comment]
i changed - \node_modules\instagram-web-api\lib\index.js
```
const createEncPassword = pwd => {
      return `#PWD_INSTAGRAM_BROWSER:0:${Date.now()}:${pwd}`
    }
```
to
```
const createEncPassword = pwd => {
      return `#PWD_INSTAGRAM_BROWSER:10:${Date.now()}:${pwd}`
    }
```
it works for me
