### ISSUE TITLE
Feature Request: searchFollowers() and searchFollowings()

### ISSUE THREAD

**Issue by umeta77** [jlobos/instagram-web-api#138]
It would be very useful to have two new functions for search `searchFollowers()` and `searchFollowings()` that would live adjacent to `getFollowers()` and `getFollowings()`.

This is possible _somewhere_ in the API as demonstrated by the official IG mobile apps (not the web app) where you can search the followers of another user while not signed in as either of those users. The same can be done for searching followings, as well we mutual friendships for the current signed in user.

![ios-follower-search](https://user-images.githubusercontent.com/66185245/83339927-189ea400-a298-11ea-907b-9ef5c85dc905.png)

See also https://mashable.com/2016/03/28/instagram-search-followers-following/

**Comment by MonsieurBibo** [comment]
This package relies on the instagram's web api (as said in his name). The mobile application probably relies on something else. If the official website doesn't use this feature, it still might be in development or simply not implemented.

However, I think you can bypass that limitation by easily fetching followers with `getFollowers()` and followings with `getFollowings()` then searching in it.

If you want mutual friends, you can just check elements of his follower/following array and compare to yours.
