### ISSUE TITLE
Getting Error on Login Logging 

### ISSUE THREAD

**Issue by rajvaya** [jlobos/instagram-web-api#141]
response is { authenticated: false, user: false, status: 'ok' }
 my user id and password are correct can anyone help me what i am doing wrong  ?
using your code as mentioned in readme.md

**Comment by codexJoin** [comment]
Make sure your code looks like this:
```js
(async() => {

	await client.login({username: 'username', password: 'password' }).then(async(response) => {

		console.log(response);
		
	});

})();
```

**Comment by rajvaya** [comment]
Issue Resolve Closing This Thank you @codexJoin
