### ISSUE TITLE
How to get all timeline_media

### ISSUE THREAD

**Issue by DJDJ326** [jlobos/instagram-web-api#151]
result of  'console.log(instagram)' is 

edge_owner_to_timeline_media: {
    count: 20,
    page_info: {
      has_next_page: true,
      end_cursor: 'abcde123==' (example)
    },
    edges: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },

I was able to get the'Like' number of 12 posts to use 'instagram.edge_owner_to_timeline_media.edges[i].node.edge_liked_by.count '
but It's only supports 12.

I want to get all timeline_media.

**Comment by mylastore** [comment]
How do I get all images and videos without using hashtags or location?

**Comment by erhancan256** [comment]
you should use cursor and nextpage
