### ISSUE TITLE
Can't Post image. Shows 403 - {"message":"API has been deprecated.","status":"fail"}

### ISSUE THREAD

**Issue by dreygur** [jlobos/instagram-web-api#159]
const Instagram = require('instagram-web-api');
const FileCookieStore = require('tough-cookie-filestore2');
const { username, password } = creds.env

const cookieStore = new FileCookieStore('./cookies.json');
const client = new Instagram({ username, password, cookieStore });

;(async () => {
    await client.login();
    const profile = await client.getProfile();

    console.log(profile);

    const photo = 'https://scontent-scl1-1.cdninstagram.com/t51.2885-15/e35/16465198_658888867648924_4042368904838774784_n.jpg'
    let { res } = await client.uploadPhoto({
        photo,
        caption: '❤️'
    });
    console.log(res);
})()

**Comment by codexJoin** [comment]
https://github.com/jlobos/instagram-web-api/pull/144

New upload photo method.

**Comment by dreygur** [comment]
Still ```UnhandledPromiseRejectionWarning: StatusCodeError: 403 - {"message":"API has been deprecated.","status":"fail"}```

I have tried installing from your repo.

**Comment by codexJoin** [comment]
Select "patch-1" and download then.

**Comment by dreygur** [comment]
Thanks @codexJoin 
It's working now :heart:

**Comment by alminisl** [comment]
> Thanks @codexJoin
> It's working now ❤️

Can you please tell what did you do ?

**Comment by EgartSites** [comment]
Old version of API key, I think 😔

**Comment by codexJoin** [comment]
I already fixed this problem, just wait for the approval of the pull to enter the official version of the api

**Comment by alminisl** [comment]
> I already fixed this problem, just wait for the approval of the pull to enter the official version of the api

Yeah thanks! I'm currently also using your branch

**Comment by revall** [comment]
Fixed in 2.2.2
