### ISSUE TITLE
homeFeed returns an empty array

### ISSUE THREAD

**Issue by hype08** [jlobos/instagram-web-api#180]
hi everyone, has anyone been able to get homeFeed working?

`  const homeFeed = await instance.getHome(
    'KGEAxpEdUwUrxxoJvxRoQeXFGooSlADHZ8UaDdSWbnOIxxoUUhyciJ7EGlxNlZjaYcUaXTgUM00qyBrgBhUsLezIGqVTlxqausga5W-fVax9xRryaBdN1EnIGvdQFgzxoMgaFoLO7v7xWQA='
  );`

when i call this, it returns an empty array []

**Comment by pedrobbarbosa** [comment]
Any progress? This is returning me 
`{ 
    data: { user: null },
    status: 'ok' 
}`

**Comment by MonsieurBibo** [comment]
Are you still facing this problem ?

**Comment by thedevankit** [comment]
@hype08 @MonsieurBibo Are you able to find any solution for it.

I tried to call homeFeed() and its return null and blank.
![image](https://user-images.githubusercontent.com/17850047/105834756-e3964d00-5ff0-11eb-90d9-2f737a0c9ee1.png)


Guy's do you know how to get home feed ?

**Comment by MonsieurBibo** [comment]
>Are you able to find any solution for it.
> 
> I tried to call homeFeed() and its return null and blank.
> ![image](https://user-images.githubusercontent.com/17850047/105834756-e3964d00-5ff0-11eb-90d9-2f737a0c9ee1.png)
> 
> 
> Guy's do you know how to get home feed ?

@thedevankit  Hey, can you recreate an issue please? This one seems inactive + it might be a different problem :) don't forget to provide your code
