### ISSUE TITLE
getting Error 429 after sending about 10 requests every 15 mintues for couple of hours

### ISSUE THREAD

**Issue by tkeidar** [jlobos/instagram-web-api#181]
After running for a couple of hours and making 8-10 requests every 15 minutes I'm getting a rate limit error:  "StatusCodeError: 429" and a long HTML string which basically says: "Error \n Please wait a few minutes before you try again."

My requests if fetching the latest photos and stories of a few specific Instagram accounts.

What the rate limit to expect?

**Comment by ronaldho** [comment]
i tried looking around, and there is no published spec that i could find either. I implemented a queue to mitigate this to retry again if it fails
