### ISSUE TITLE
TypeError: Cannot read property 'user' of undefined

### ISSUE THREAD

**Issue by austinkimchi** [jlobos/instagram-web-api#198]
The code I have been using has been working in the morning but after 2 hours of coding it seemed to stop after I tested it.

I tested with this code:
`const Instagram = require('instagram-web-api')
const { username, password } = process.env

const client = new Instagram({ username, password });
const instagram = await client.getUserByUsername({ username: 'instagram' })
`
Then I get the error: 
![image](https://user-images.githubusercontent.com/40729751/100013325-83cdbc80-2d89-11eb-9a81-da14d461a6ac.png)

I used runkit to test this out to make sure my code wasn't wrong or anything....

![image](https://user-images.githubusercontent.com/40729751/100013352-8fb97e80-2d89-11eb-9526-c915358a754a.png)

Please help. I don't know if this is because of Instagram API down or anything but my earlier it was working. I tried changing IP address aswell and still errored out.

**Comment by KevinYap** [comment]
i also having this issue, anyone can help on this?

**Comment by austinkimchi** [comment]
I have spent multiple hours trying to find the issue but can't. I'm not sure what exactly is the problem but please help.

**Comment by KevinYap** [comment]
I get this error in my terminal:
error - ./node_modules/instagram-web-api/lib/index.js:2:0
Module not found: Can't resolve 'fs'

**Comment by JCGithu** [comment]
Getting the same error

..\node_modules\instagram-web-api\lib\index.js:152
    }).then(data => data.graphql.user)
TypeError: Cannot read property 'user' of undefined


EDIT: So my solution was a stupid one. I forgot password was case-senstive so was inputting that wrong. I would recommend double-checking your log-in info and cookies.

**Comment by 3yezz** [comment]
Hello
No solution for the moment?
![image](https://user-images.githubusercontent.com/38151302/102660286-2f7fe780-4151-11eb-8379-9d065d74a318.png)

**Comment by OlivierDijkstra** [comment]
Got the same error, login credentials are working fine. 
`
console.log('Credentials', process.env.INSTA_USER, process.env.INSTA_PASS);

    const client = new Instagram({
      username: process.env.INSTA_USER,
      password: process.env.INSTA_PASS
    });

    let performImageFetch = true;

    try {
      console.log('logging in 🔒...');

      await client.login();

      console.log('Login successfull ✅');
    } catch (err) {
      performImageFetch = false;

      console.log('Login failed 🚫');

      if (err.status === 403) {
        console.log('Throttled 🚫');

        return;
      }

      if (err.error && err.error.message === 'checkpoint_required') {
        console.log('Challenge failed!', 'Performing new challenge...');

        const challengeUrl = err.error.checkpoint_url;
        await client.updateChallenge({ challengeUrl, choice: 1 });

        performImageFetch = true;
      }
    }

    if (performImageFetch) {
      console.log('Getting photos 📸... ');

      client
        .getPhotosByUsername({
          username: 'scorpiomodelmanagement'
        })
        .then((response) => {
          // console.log(response);
          console.log('Images received ✅');
          posts = response.user.edge_owner_to_timeline_media.edges;
        })
        .catch((error) => {
          console.log('Failed getting images 🚫');

          console.log(error);
        });
}
`

Fails when I try to get the images using `getPhotosByUsername`. Fails on `this.getUserByUsername` because user is undefined.

**Comment by Zegoverno** [comment]
Same error here when using getFollowings and getUserByUsername... everything was working before a block from instagram, using the account is working fine, but with the library functions not

**Comment by Zegoverno** [comment]
I could fix that by removing the cookie from auth, working fine now

**Comment by KevinYap** [comment]
> I could fix that by removing the cookie from auth, working fine now

do you mind share your code here? regarding on how to remove the cookie from auth, thanks!

**Comment by bvrls** [comment]
still no update?

**Comment by banguncode** [comment]
> The code I have been using has been working in the morning but after 2 hours of coding it seemed to stop after I tested it.
> 
> I tested with this code: `const Instagram = require('instagram-web-api') const { username, password } = process.env
> 
> const client = new Instagram({ username, password }); const instagram = await client.getUserByUsername({ username: 'instagram' }) ` Then I get the error: ![image](https://user-images.githubusercontent.com/40729751/100013325-83cdbc80-2d89-11eb-9a81-da14d461a6ac.png)
> 
> I used runkit to test this out to make sure my code wasn't wrong or anything....
> 
> ![image](https://user-images.githubusercontent.com/40729751/100013352-8fb97e80-2d89-11eb-9526-c915358a754a.png)
> 
> Please help. I don't know if this is because of Instagram API down or anything but my earlier it was working. I tried changing IP address aswell and still errored out.

1. Create environment file `.env`
2. Fill `username=?` and `password=?`
3. Install `npm i dotenv`
4. Import `const dotenv = require("dotenv"); dotenv.config();`
5. Try again

**Comment by austinkimchi** [comment]
Never figured out and tried everything but I'm using another module to power this.

**Comment by joris-delorme** [comment]
@PrincessKimchi what is the module you use ?
