### ISSUE TITLE
[Question] disk usage with uploadPhoto 

### ISSUE THREAD

**Issue by sjagoori** [jlobos/instagram-web-api#208]
In the [example](https://github.com/jlobos/instagram-web-api#uploadphotoparams), the upload takes a remote URL to an image. I tried reading [the function in the library](https://github.com/jlobos/instagram-web-api/blob/e85a0f603e5be9e147606feed73a5057d74c5c60/lib/index.js#L439) regarding the uploads and figured that it's only passing the URL to Instagram. So my question is: does the library actually send URLs to Instagram or does it download and then upload it?

**Comment by codexJoin** [comment]
The api, requires the image in a buffer, and sends that buffer to instagram, does not take up space on your disk.

**Comment by sjagoori** [comment]
That answers my question, thank you so much!
