### ISSUE TITLE
data.graphql returning undefined in getUserByUsername function

### ISSUE THREAD

**Issue by CyberShuri** [jlobos/instagram-web-api#214]
5 minutes ago I started noticing an odd error that stated that it cannot read property "user" of undefined, when I looked into it, it was a malfunction of the getUserByUsername function that caused data.graphql to return undefined.

**Comment by MonsieurBibo** [comment]
Can you provide more details ? I just tested and it works on my computer.

**Comment by CyberShuri** [comment]
Upon trying to use the getPhotosByUsername function I receive this error which is connected to the getUserByUsername function

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'user' of undefined
    at C:\Users\epicd\Desktop\typescript discord bot\node_modules\instagram-web-api\lib\index.js:152:34
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Instagram.getPhotosByUsername (C:\Users\epicd\Desktop\typescript discord bot\node_modules\instagram-web-api\lib\index.js:215:18)
```

**Comment by MonsieurBibo** [comment]
Can you provide your code please?

**Comment by CyberShuri** [comment]
This is the code used
```node
        const instaClient = new Instagram({ instaName, instaPassword })
        await instaClient.login()

        setInterval(async () => {
            const cookies = JSON.parse(readFileSync('./cookies.json', 'utf8'))

            const posts = await instaClient.getPhotosByUsername({ username: 'rulesfortheboys' })

            if (posts.user.edge_owner_to_timeline_media.count > cookies.lastPostCount) {
                cookies.lastPostCount++;
                
                const shortcode = posts.user.edge_owner_to_timeline_media.edges[0].node.shortcode
                const link = `https://www.instagram.com/p/${shortcode}`

                const channel = await client.channels.fetch('794304862997315584') as TextChannel;
                channel.send(link)

                writeFile('./cookies.json', JSON.stringify(cookies, null, 4), (err) => {
                    if (err) console.log(err);
                })
            }
        }, 5000)
```

**Comment by CyberShuri** [comment]
Sorry about that, it seems like it was an interference between TypeScript's import and JavaScript's require which caused the code to malfunction.

**Comment by CyberShuri** [comment]
Upon closer research, I have seen that it redirects me to the Instagram Login page, even if I login into the account first.

**Comment by ryanmichaelhirst** [comment]
@CyberShuri You can use the `sendChallenge` and then the `verifyChallenge` method to fix this

**Comment by CyberShuri** [comment]
Thank you, rmbh. Issue closed

**Comment by baptisteArno** [comment]
Please can you elaborate on `sendChallenge` and `verifyChallenge`? I can't find these in the documentation. I have this issue popping randomly

**Comment by erhancan256** [comment]
did you fix ?
