### ISSUE TITLE
StatusCodeError: 400 You need an email or confirmed phone number

### ISSUE THREAD

**Issue by spacevx** [jlobos/instagram-web-api#223]
Hey i have this message error StatusCodeError: 400 - {"message":{"errors":["You need an email or confirmed phone number."]},"status":"fail"} (if i print getProfile() for example that going to work)

i just tried to take the example, but impossible to update the profile
```javascript

const Instagram = require('instagram-web-api');
const username = 'myusername';
const password = 'mypassword';

const client = new Instagram({ username, password });

(async () => {
    await client.login()
    const profile = await client.getProfile()

    await client.updateProfile({ biography: '❤️', website: 'https://jlobos.com/', gender: 1 })
  
    console.log(profile)
  })()

**Comment by MonsieurBibo** [comment]
Does your account have a confirmed e-mail/phone number?

**Comment by spacevx** [comment]
Yeah my account have a confirmed e-mail/phone number

**Comment by VeqsaGit** [comment]
I have the same problem

**Comment by spacevx** [comment]
> I have the same problem

This api must be outdated
