### ISSUE TITLE
New `client.getHome` endpoint

### ISSUE THREAD

**Issue by timolins** [jlobos/instagram-web-api#23]
It seems like Instagram ist testing a new endpoint instead of `/?__a=1`. My personal account returns the expected result, my test account on the other hand returns `{ "graphql": null }`.
After some investigation I think they are switching to the GraphQL endpoint for this task.

Not sure what to do at this point since it isn't really consistent yet. I will just put this out here for now.

**Comment by revall** [comment]
Fixed by https://github.com/jlobos/instagram-web-api/pull/70
