### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by DerLomo** [jlobos/instagram-web-api#231]
Can´t install because it seems de repo have the same name that the package:
![image](https://user-images.githubusercontent.com/25827889/109079616-7b29b100-76ff-11eb-9ec8-9b6914253ac5.png)

I have to be honest I am quite noob with javascript

**Comment by MonsieurBibo** [comment]
I'm not sure, but I would say this happens when the name in `package.json` is the same as the package you want to install.
