### ISSUE TITLE
Get ID

### ISSUE THREAD

**Issue by DerLomo** [jlobos/instagram-web-api#234]
I am reading the docs but can´t understand what you refer by ID, for example for liking a photo I have to know the Id, how i get this id, or the user id?
By the link?
Thanks

**Comment by MonsieurBibo** [comment]
Hey, you can get the mediaId by using the [`getMediaByShortcode()` method](https://github.com/jlobos/instagram-web-api/blob/e85a0f603e5be9e147606feed73a5057d74c5c60/lib/index.js#L481). You just need to fetch the id property, which is the mediaId !

Here is a quick example: 
```
;(async () => {
  await client.login()
  const media = await client.getMediaByShortcode({shortcode: "" }) // Provide your media's shortcode.
  console.log(`The mediaId is ${media.id} !`)
})()
```

**Comment by DerLomo** [comment]
So in x where 
 {shortcode : " x " }
Have I to put the link of media/profile?

**Comment by MonsieurBibo** [comment]
No, the shortcode is algorithmically linked to the mediaId. The shortcode can be easily found in the URL of your post.

For example: the shortcode in `www.instagram.com/p/CLNnZeZJnon/` is `CLNnZeZJnon`

**Comment by DerLomo** [comment]
> 
> 
> No, the shortcode is algorithmically linked to the mediaId. The shortcode can be easily found in the URL of your post.
> 
> For example: the shortcode in `www.instagram.com/p/CLNnZeZJnon/` is `CLNnZeZJnon`

Yes but aplied to a profile, the link is https://www.instagram.com/examplename/ examplename is the shortcode?

**Comment by MonsieurBibo** [comment]
No it's not.  However you can get userId from username like this:

```js
const Instagram = require('instagram-web-api')
const { username, password } = process.env
const client = new Instagram({ username, password })
;(async () => {
  await client.login()
  // Replace desiredUsername by your desired username
  const user = await client.getUserByUsername({ username: "desiredUsername"})
  console.log(`${username}'s id is ${user.id} !`)
})()
```

I've created a PR about usages examples (#221).
