### ISSUE TITLE
Put text and links n stor

### ISSUE THREAD

**Issue by DerLomo** [jlobos/instagram-web-api#236]
I have tested how the caption in the : 
`const { media } = await client.uploadPhoto({ photo: photo, caption, post: 'feed' })`
Worked as the photo in feed appear with caption, but when it comes to story mode the project totally ignores the caption info.
The same goes for the link, it´s possible to add a link in the story ?
Not like a plain text but like the stories that contain links and direcct you to a certain post?

**Comment by MonsieurBibo** [comment]
You can't add captions to your stories because this parameter seems to be dedicated to the feed option.

**Comment by DerLomo** [comment]
> 
> 
> You can't add captions to your stories because this parameter seems to be dedicated to the feed option.

Oc I already figuret that out.
What I am asking is how to put text on stories.
Furthermore what seems more intersting is to share feed posts or just posts as stories
