### ISSUE TITLE
[getUserByUsername] Cannot read property 'user' of undefined with valid user

### ISSUE THREAD

**Issue by wemersonrv** [jlobos/instagram-web-api#239]
Hello,

i'm receiving the message `Cannot read property 'user' of undefined` when try to run the function **getUserByUsername**

```js
const cookieStore = new FileCookieStore('./session.json')

const client = new Instagram({
   username: 'my-username',
   password: 'mypassword',
   cookieStore,
})

await client.login()

const user = await client.getUserByUsername({
   username: client.credentials.username,
})
```

```bash
TypeError: Cannot read property 'user' of undefined
    at D:\DadosImportantes\dev\Projetos\WemersonRV\insta-stories-test\node_modules\instagram-web-api\lib\index.js:152:34
```

**Comment by MonsieurBibo** [comment]
This package isn't really maintained anymore. However, it might be connected to your #238 issue.

**Comment by schimini** [comment]
@wemersonrv have you tried deleting the `session.json` file and restart?

**Comment by wemersonrv** [comment]
> @wemersonrv have you tried deleting the `session.json` file and restart?

Hello. Nope. I was just testing this package and as was told it maintained anymore, i stop using it!
