### ISSUE TITLE
Config a proxy with user and passwords

### ISSUE THREAD

**Issue by DerLomo** [jlobos/instagram-web-api#243]
I know that is defined in the docs how to config a proxy, but when the proxy comes with user and passwords is not defined,
Does anybody know how to config in this case?

**Comment by MonsieurBibo** [comment]
I don't use proxies but I think you can use your credentials in the proxy's url like [this.](https://github.com/request/request-promise/issues/130#issuecomment-267528293)

**Comment by raginisahu** [comment]
You can use the proxy like this

const client = new Instagram({ username, password },{proxy: 'http://username:password@proxyurl:proxyport'})

username, password, proxyurl and proxyport need to be change respectively.
