### ISSUE TITLE
feedback_required

### ISSUE THREAD

**Issue by kkm** [jlobos/instagram-web-api#246]
after trying to login I got the error message
what does that mean?

![image](https://user-images.githubusercontent.com/134290/115132617-148b8a00-a002-11eb-8139-2e02d1135544.png)

**Comment by MonsieurBibo** [comment]
see #216

**Comment by kkm** [comment]
thanks, it is very interesting when I log in to chrome instagram works well.
only your code is different, can you tell me what's the difference?

**Comment by MonsieurBibo** [comment]
As I said in the other issue, Instagram can detect spam or automated actions. However, this library is poorly maintained and could have some design flaws (like important headers missing) which can lead Instagram to think it's malicious.

**Comment by kkm** [comment]
Okay it works well again now after maybe in 24h?
