### ISSUE TITLE
Post stories with text

### ISSUE THREAD

**Issue by DerLomo** [jlobos/instagram-web-api#247]
It would be amazing if someone knows how to put text on stories adding @users so the viewers could click and go to the user profile.

**Comment by MonsieurBibo** [comment]
This package doesn't allow you to do so for the moment. It's rarely updated and poorly maintained, you should use another one for any serious project.

**Comment by DerLomo** [comment]
> 
> 
> This package doesn't allow you to do so for the moment. It's rarely updated and poorly maintained, you should use another one for any serious project.

Could you suggest me other projects?
I am hardly finding something that works

**Comment by MonsieurBibo** [comment]
Try [that](https://github.com/dilame/instagram-private-api)
