### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by keremsirin** [jlobos/instagram-web-api#255]
Hi, firstly thanks for the repo. I tried to use the `getUserByUserName` method and it works clearly but when I try to get data over and over it says `UnhandledPromiseRejectionWarning: StatusCodeError: 403 - {"message":"Please wait a few minutes before you try again.","status":"fail"}` 

PS: I am authenticating with an account that I just created 2 days ago.

Here is my code:
```
const Instagram = require('instagram-web-api')
const username = 'xxxxxx'
const password = 'xxxxxx'

const client = new Instagram({ username, password })
const userName = 'instagram'
;(async () => {
  await client.login()
  const profile = await client.getUserByUsername({ username: userName })
  console.log(profile)
  await client.logout()
})()
```

**Comment by MonsieurBibo** [comment]
See #216 #238 #239
