### ISSUE TITLE
"authenticated": false" when client.login

### ISSUE THREAD

**Issue by svrem** [jlobos/instagram-web-api#285]
When I run the `await client.login()`, I get as return value like this: `{ user: true, authenticated: false, status: 'ok' }`. 
After that if I run the command `client.uploadPhoto({ ... })` I get an error saying: `{"message":"login_required","status":"fail"}`.

Does anyone know how to fix this?

**Comment by hailovigor** [comment]
Have you solved this problem?

**Comment by Freccia** [comment]
I have the same error. Any suggestion?

**Comment by Freccia** [comment]
I used a proxy to see the requests.
The login request seem to be ok, but then posting a photo does not work, I get the 403 error.

<img width="1309" alt="Screenshot 2022-10-10 at 14 08 13" src="https://user-images.githubusercontent.com/15819880/194863276-fac1ddc1-8fd0-45a1-b4dd-5fe2469067b2.png">


<img width="1305" alt="Screenshot 2022-10-10 at 14 10 28" src="https://user-images.githubusercontent.com/15819880/194863535-2a19ac40-5c3d-49f3-8e66-9b24ef5ec265.png">


Any ideas of what is going wrong ?

**Comment by scrapguru** [comment]
it's cuz of bad password encryption, if you need help contact me on telegram t.me/scrapguru
