### ISSUE TITLE
login failed: TypeError: Cannot read properties of null (reading '0')

### ISSUE THREAD

**Issue by infysumanta** [jlobos/instagram-web-api#298]
$ node test.js
\node_modules\instagram-web-api\lib\index.js:57
      value = matches[0].substring(13)
                     ^

TypeError: Cannot read properties of null (reading '0')
    at \node_modules\instagram-web-api\lib\index.js:57:22
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Instagram.login (\node_modules\instagram-web-api\lib\index.js:54:5)

$ node test.js
\node_modules\instagram-web-api\lib\index.js:57
      value = matches[0].substring(13)
                     ^

TypeError: Cannot read properties of null (reading '0')
    at \node_modules\instagram-web-api\lib\index.js:57:22
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Instagram.login (\node_modules\instagram-web-api\lib\index.js:54:5)
    at async instapost\test.js:7:3

**Comment by tusharsinghal1610** [comment]
i also started facing today only.

**Comment by tusharsinghal1610** [comment]
here is the solution :

https://github.com/jlobos/instagram-web-api/issues/296 @infysumanta

**Comment by infysumanta** [comment]
thanks a lot @tusharsinghal1610
