### ISSUE TITLE
Get followers and followings

### ISSUE THREAD

**Issue by TheZanki** [jlobos/instagram-web-api#5]
Thank you very much your api is super!

I would very much like to see support getting subscribers
But not only their own but also any other person like
```
let followers = getFollowers (userId);
console.log (followers);
```

output:
```
[
Lucas123,
anotherPerson,
MeganFox,
Lena23
]
```

**Comment by timolins** [comment]
I agree, this would be useful feature.
It seems like the web app uses the `/graphql/query/` endpoint to get this data.

There are two things holding me back right now, which I don't fully understand:

1. Both request use a query paremter called `query_hash` to define which data is needed. In my case they are `37479f2b8209594dde7facb0d904896a` for followers and `58712303d941c6855d4e888c5f0cd22f ` for followings. Not sure if they will change, but they can be found hard coded in [one of their bundles](https://www.instagram.com/static/bundles/base/Consumer.js/6945672b0d17.js). Maybe it is safe for use them as well.
2. For pagination they use an `after` property in their GraphQL query. This isn't a human readable value though, rather something that looks like a cryptographic string. Maybe someone else can find out more on this topic and find a way to make use of this!
