### ISSUE TITLE
unhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by D3fau1t** [jlobos/instagram-web-api#54]
node -v 8.11.3
Code:
const Instagram = require('instagram-web-api')
const client = new Instagram({ username: '', password: '' })
;(async () => {
  await client.login()
  const profile = await client.getProfile()
  console.log(profile)
})()
Error:
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at request.then.res (/Users/user/Desktop/prjct/htdocs/app/node_modules/instagram-web-api/lib/index.js:55:46)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:9012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9012) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by wixvii** [comment]
How could you fix this issue ?

**Comment by erhancan256** [comment]
'user' of undefined hatası aldın mı hiç ?
