### ISSUE TITLE
Error: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by D3fau1t** [jlobos/instagram-web-api#55]
node -v 8.11.3
Code:
const Instagram = require('instagram-web-api')
const client = new Instagram({ username: '', password: '' })
;(async () => {
await client.login()
const profile = await client.getProfile()
console.log(profile)
})()
Error:
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
at request.then.res (/Users/user/Desktop/prjct/htdocs/app/node_modules/instagram-web-api/lib/index.js:55:46)
at 
at process._tickCallback (internal/process/next_tick.js:188:7)
(node:9012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9012) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ozican** [comment]
up

**Comment by simvolice** [comment]
Add to Header param : 'cookie': 'ig_cb=1'
![image](https://user-images.githubusercontent.com/5946300/50218543-86158800-03b6-11e9-98f8-dcec4749c239.png)

And change URL: 
![image](https://user-images.githubusercontent.com/5946300/50218577-9c234880-03b6-11e9-99da-52dc6db060e1.png)
