### ISSUE TITLE
fixed getHome()

### ISSUE THREAD

**Issue by mikehumix** [jlobos/instagram-web-api#57]
the old
`getHome() {
    return this.request('/?__a=1').then(data => data.graphql.user)
  }`

the new
`getHome(variables) {
    return this.request('/graphql/query/', {
      qs: {
        query_hash: 'your_query_id',
        variables: JSON.stringify(variables)
      }
    })
      .then(data => data)
  }`

https://www.instagram.com/graphql/query/?query_hash=your_query_id&variables={"fetch_media_item_count":12,"fetch_media_item_cursor":end_cursor}

**Comment by revall** [comment]
Fixed by https://github.com/jlobos/instagram-web-api/pull/70
