### ISSUE TITLE
How get all subscribers ?

### ISSUE THREAD

**Issue by kokomola** [jlobos/instagram-web-api#68]
Hi ! Now is limite 50, how get more ?

**Comment by KimAlexander** [comment]
@kokomola you have to provide an `after` param to reques and request again

**Comment by mkgerasimenko** [comment]
@KimAlexander, could you please provide more info about this param? What I should insert into this param? Thank you!

**Comment by kokomola** [comment]
@mkgerasimenko After receiving JSON you need insert **end_cursor** field into **after** param.
<img width="968" alt="Снимок экрана 2019-06-05 в 23 47 42" src="https://user-images.githubusercontent.com/29233138/58974405-8383df00-87ec-11e9-8aac-1117f7c6822a.png">

**Comment by MonsieurBibo** [comment]
Are you still having this issue ? If not can you close this issue please ?
